/**
 * Comprehensive synonym map for converting modern/common terms to formal CCC equivalents
 * This helps improve search relevance by mapping casual language to official terminology
 * and reduces OpenAI API calls by handling common rewrites locally
 */
export const synonymMap: Record<string, string[]> = {
  // Sexual ethics and relationships
  gay: ["homosexual", "homosexuality"],
  "gay marriage": ["homosexual union", "same-sex union"],
  lesbian: ["homosexual", "homosexuality"],
  lgbt: ["homosexual", "homosexuality"],
  lgbtq: ["homosexual", "homosexuality"],
  "same sex marriage": ["homosexual union", "same-sex union"],
  "same-sex marriage": ["homosexual union", "same-sex union"],
  queer: ["homosexual", "homosexuality"],

  // Life issues
  abortion: ["procured abortion"],
  "birth control": ["contraception"],
  "the pill": ["contraception", "contraceptive"],
  condoms: ["contraception", "contraceptive"],
  contraceptives: ["contraception"],
  "family planning": ["contraception", "responsible parenthood"],
  "planned parenthood": ["contraception", "responsible parenthood"],
  euthanasia: ["end of life", "dying", "death"],
  "assisted suicide": ["end of life", "dying", "death"],
  ivf: ["assisted reproduction", "fertility"],
  "in vitro fertilization": ["assisted reproduction", "fertility"],
  "stem cell": ["human embryo", "human life"],
  cloning: ["human embryo", "human dignity"],

  // Sexual morality
  "sex before marriage": ["fornication"],
  "premarital sex": ["fornication"],
  "living together": ["cohabitation"],
  "shacking up": ["cohabitation"],
  adultery: ["adultery", "infidelity"],
  cheating: ["adultery", "infidelity"],
  affair: ["adultery", "infidelity"],
  prostitution: ["commercialized vice"],
  pornography: ["lust", "chastity"],
  masturbation: ["solitary pleasure", "chastity"],
  hookup: ["fornication", "chastity"],
  "one night stand": ["fornication", "chastity"],

  // Modern terminology for traditional concepts
  gender: ["sexual identity", "masculinity", "femininity"],
  transgender: ["sexual identity"],
  "gender identity": ["sexual identity", "masculinity", "femininity"],
  "non-binary": ["sexual identity"],
  divorce: ["dissolution of marriage", "separation"],
  remarriage: ["subsequent marriage"],
  "single parent": ["family", "motherhood", "fatherhood"],
  "blended family": ["family", "marriage"],

  // Science and academic terms
  physics: ["natural science", "science", "creation"],
  chemistry: ["natural science", "science", "creation"],
  biology: ["natural science", "science", "life", "creation"],
  evolution: ["creation", "natural science", "human origin"],
  "big bang": ["creation", "universe", "cosmology"],
  genetics: ["human life", "creation", "natural science"],
  psychology: ["human person", "soul", "mind"],
  psychiatry: ["human person", "soul", "mental health"],
  therapy: ["healing", "pastoral care"],
  counseling: ["pastoral care", "guidance"],
  philosophy: ["wisdom", "truth", "reason"],
  science: ["natural science", "creation", "truth"],

  // Social and political issues
  poverty: ["poor", "needy", "destitute"],
  homeless: ["poor", "needy"],
  "social justice": ["justice", "social doctrine"],
  inequality: ["injustice", "oppression"],
  racism: ["prejudice", "discrimination", "human dignity"],
  sexism: ["discrimination", "human dignity"],
  feminism: ["women", "human dignity", "equality"],
  capitalism: ["economic system", "private property"],
  socialism: ["economic system", "social doctrine"],
  communism: ["economic system", "social doctrine"],
  globalization: ["international order", "social doctrine"],
  immigration: ["migration", "hospitality", "stranger"],
  refugee: ["migration", "hospitality", "stranger"],
  welfare: ["social assistance", "solidarity"],
  healthcare: ["healing", "medical care", "human dignity"],
  education: ["formation", "teaching", "wisdom"],
  politics: ["political community", "common good"],
  government: ["political authority", "common good"],
  democracy: ["political participation", "common good"],
  voting: ["political participation", "civic duty"],

  // Environmental and ecological terms
  environment: ["creation", "stewardship"],
  "climate change": ["creation", "stewardship", "ecology"],
  "global warming": ["creation", "stewardship", "ecology"],
  pollution: ["creation", "stewardship"],
  ecology: ["creation", "stewardship"],
  conservation: ["stewardship", "creation"],
  sustainability: ["stewardship", "creation"],
  animals: ["creatures", "creation"],
  nature: ["creation", "natural world"],

  // Technology and modern life
  internet: ["communication", "media"],
  "social media": ["communication", "media"],
  "artificial intelligence": ["human reason", "technology"],
  ai: ["human reason", "technology"],
  robots: ["technology", "human work"],
  automation: ["technology", "human work"],
  "genetic engineering": ["human life", "creation"],
  biotechnology: ["human life", "creation"],
  "nuclear weapons": ["war", "peace", "weapons"],
  cyber: ["technology", "communication"],

  // Economic terms
  money: ["wealth", "material goods"],
  wealth: ["riches", "material goods"],
  rich: ["wealthy", "material goods"],
  business: ["work", "economic activity"],
  job: ["work", "labor"],
  career: ["work", "vocation"],
  unemployment: ["work", "economic hardship"],
  debt: ["economic obligation", "justice"],
  taxes: ["civic duty", "common good"],
  charity: ["almsgiving", "love of neighbor"],
  donation: ["almsgiving", "generosity"],
  volunteering: ["service", "love of neighbor"],

  // Religious terms (expanded)
  mass: ["eucharist", "holy sacrifice", "liturgy"],
  priest: ["presbyter", "clergy", "minister"],
  pastor: ["priest", "shepherd", "clergy"],
  minister: ["clergy", "priest", "servant"],
  pope: ["pontiff", "holy father", "bishop of rome"],
  bishop: ["episcopal", "successor of apostles"],
  cardinal: ["prince of church", "episcopal"],
  deacon: ["diaconate", "ministry"],
  nun: ["religious sister", "consecrated life"],
  monk: ["religious brother", "consecrated life"],
  bible: ["scripture", "holy scripture", "word of god"],
  church: ["ecclesia", "body of christ", "people of god"],
  cathedral: ["church", "episcopal see"],
  parish: ["church", "community"],
  chapel: ["church", "prayer"],
  monastery: ["religious house", "consecrated life"],
  convent: ["religious house", "consecrated life"],
  seminary: ["priestly formation", "clerical training"],

  // Theological concepts
  god: ["divine", "almighty", "creator"],
  jesus: ["christ", "lord", "savior"],
  "holy spirit": ["spirit", "paraclete", "advocate"],
  trinity: ["triune god", "three persons"],
  heaven: ["eternal life", "beatific vision"],
  hell: ["eternal punishment", "damnation"],
  purgatory: ["purification", "final purification"],
  soul: ["spiritual", "immortal soul"],
  spirit: ["spiritual", "soul"],
  grace: ["divine grace", "sanctifying grace"],
  salvation: ["redemption", "eternal life"],
  redemption: ["salvation", "atonement"],
  incarnation: ["word made flesh", "divine humanity"],
  resurrection: ["rising from dead", "eternal life"],
  ascension: ["glorification", "exaltation"],
  revelation: ["divine revelation", "word of god"],
  tradition: ["sacred tradition", "apostolic tradition"],

  // Moral concepts (expanded)
  sin: ["transgression", "offense", "fault", "moral evil"],
  evil: ["wickedness", "malice", "moral disorder"],
  good: ["virtue", "righteousness", "moral good"],
  virtue: ["moral excellence", "good habit"],
  vice: ["moral defect", "bad habit"],
  conscience: ["moral conscience", "interior voice"],
  guilt: ["moral responsibility", "fault"],
  shame: ["moral awareness", "conscience"],
  forgiveness: ["mercy", "reconciliation"],
  repentance: ["contrition", "conversion"],
  conversion: ["metanoia", "turning to god"],
  temptation: ["trial", "moral test"],
  suffering: ["trial", "cross", "redemptive suffering"],
  sacrifice: ["offering", "self-gift"],
  love: ["charity", "caritas", "agape"],
  hate: ["malice", "enmity"],
  anger: ["wrath", "ire"],
  pride: ["arrogance", "vanity"],
  humility: ["meekness", "lowliness"],
  greed: ["avarice", "covetousness"],
  envy: ["jealousy", "covetousness"],
  sloth: ["laziness", "acedia"],
  gluttony: ["excess", "intemperance"],
  lust: ["concupiscence", "disordered desire"],

  // Sacramental life (expanded)
  baptism: ["baptismal", "initiation", "rebirth"],
  confirmation: ["chrismation", "strengthening"],
  marriage: ["matrimony", "conjugal union", "wedlock"],
  wedding: ["marriage", "matrimony"],
  confession: ["penance", "reconciliation", "absolution"],
  communion: ["eucharist", "holy communion"],
  "last rites": ["anointing of the sick", "extreme unction"],
  ordination: ["holy orders", "priesthood"],
  funeral: ["burial", "christian burial"],
  blessing: ["benediction", "consecration"],
  consecration: ["sanctification", "dedication"],

  // Prayer and spirituality (expanded)
  prayer: ["petition", "intercession", "contemplation", "worship"],
  worship: ["adoration", "liturgy", "divine worship"],
  meditation: ["contemplation", "reflection", "mental prayer"],
  contemplation: ["mystical prayer", "union with god"],
  fasting: ["abstinence", "penance", "mortification"],
  pilgrimage: ["spiritual journey", "devotion"],
  retreat: ["spiritual exercises", "recollection"],
  devotion: ["piety", "religious practice"],
  rosary: ["marian prayer", "prayer beads"],
  novena: ["nine days prayer", "devotional prayer"],
  litany: ["prayer of petition", "invocation"],
  hymn: ["sacred song", "psalm"],
  psalm: ["sacred song", "prayer"],
  scripture: ["bible", "word of god"],
  gospel: ["good news", "evangel"],
  sermon: ["homily", "preaching"],
  homily: ["preaching", "instruction"],

  // Feast days and seasons
  christmas: ["nativity", "incarnation"],
  easter: ["resurrection", "paschal mystery"],
  pentecost: ["holy spirit", "church birth"],
  advent: ["preparation", "coming"],
  lent: ["penance", "preparation", "fasting"],
  "holy week": ["passion week", "paschal mystery"],
  "good friday": ["crucifixion", "passion"],
  "palm sunday": ["passion sunday", "triumphal entry"],
  epiphany: ["manifestation", "revelation"],
  assumption: ["mary", "blessed virgin"],
  "immaculate conception": ["mary", "blessed virgin"],
  "all saints": ["communion of saints", "holy ones"],
  "all souls": ["faithful departed", "purgatory"],

  // Modern challenges and issues
  addiction: ["vice", "disorder", "healing"],
  depression: ["suffering", "mental illness", "healing"],
  anxiety: ["worry", "trust", "peace"],
  stress: ["burden", "peace", "rest"],
  burnout: ["exhaustion", "rest", "sabbath"],
  loneliness: ["solitude", "community", "friendship"],
  isolation: ["solitude", "community"],
  bullying: ["oppression", "violence", "dignity"],
  abuse: ["violence", "harm", "protection"],
  "domestic violence": ["family violence", "protection"],
  "sexual abuse": ["violation", "harm", "healing"],
  trauma: ["wound", "healing", "recovery"],
  healing: ["restoration", "wholeness", "health"],
  recovery: ["healing", "restoration"],
  wellness: ["health", "wholeness"],
  fitness: ["health", "body", "stewardship"],
  diet: ["food", "temperance", "health"],
  exercise: ["physical activity", "health", "stewardship"],

  // Other religions and spiritual traditions
  buddhism: ["non-christian religion", "eastern religion", "false religion"],
  buddha: ["false god", "idol", "non-christian"],
  buddhist: ["non-christian", "pagan"],
  hinduism: ["non-christian religion", "eastern religion", "false religion"],
  hindu: ["non-christian", "pagan"],
  islam: ["non-christian religion", "monotheism", "false religion"],
  muslim: ["non-christian", "islamic"],
  judaism: ["jewish religion", "old covenant"],
  jewish: ["jewish people", "chosen people"],
  atheism: ["denial of god", "godlessness"],
  atheist: ["non-believer", "godless"],
  agnostic: ["doubt", "uncertainty", "non-believer"],
  "new age": ["false spirituality", "occult", "superstition"],
  occult: ["superstition", "false spirituality", "darkness"],
  witchcraft: ["occult", "superstition", "magic"],
  magic: ["superstition", "occult"],
  astrology: ["superstition", "divination"],
  horoscope: ["superstition", "astrology"],
  reincarnation: ["false belief", "afterlife"],
  karma: ["false belief", "moral consequence"],
  nirvana: ["false salvation", "eastern spirituality"],
  enlightenment: ["false illumination", "wisdom", "truth"],
  
  // Yoga and meditation practices
  yoga: ["physical exercise", "eastern spirituality", "meditation"],
  yogi: ["practitioner", "eastern spirituality"],
  "yoga poses": ["physical exercise", "stretching"],
  asanas: ["yoga poses", "physical exercise"],
  pranayama: ["breathing", "meditation"],
  chakras: ["false spirituality", "energy centers"],
  kundalini: ["false spirituality", "energy"],
  mantra: ["repetitive prayer", "chanting"],
  "transcendental meditation": ["meditation", "eastern spirituality"],
  mindfulness: ["awareness", "attention", "contemplation"],
  zen: ["buddhist meditation", "eastern spirituality"],
  "martial arts": ["physical discipline", "self-defense"],
  "tai chi": ["physical exercise", "eastern practice"],
  qigong: ["physical exercise", "energy practice"],
  acupuncture: ["alternative medicine", "healing"],
  "alternative medicine": ["natural healing", "holistic health"],
  crystals: ["superstition", "false healing"],
  "energy healing": ["false healing", "superstition"],
};
